import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navigation from "./components/navigation";
import { useState, useEffect } from "react";
import Footer from "./components/footer";

const REFERENCES =
[
  {quote:"From beautiful ballads to raging rock and back again... elloquently excecutes each song with a dilligence audiences will come to expect", author:"The Tufts Daily"},
  {quote:"Testing a second quote", author:"The Tufts Daily"},
  {quote:"Testing a third quote", author:"The Tufts Daily"}
]
const BIO = "Matthew Torres is a recent graduate of Tufts University, in Meford, MA. "

function reveal() {
  var reveals = document.querySelectorAll(`.${styles.headerImage}, .${styles.pageTitle}`);
  console.log(reveals);
  for (var i = 0; i < reveals.length; i++) {
    var windowHeight = window.innerHeight;
    var elementTop = reveals[i].getBoundingClientRect().top;
    var elementVisible = 200;
    if (elementTop < windowHeight - elementVisible) {
      reveals[i].classList.add(styles.active);
    }
  }
}

export default function Home() {
  const [hydrated, setHydrated] = useState(false);
  const [displayedReference, setDisplayedReference] = useState(0);
  setTimeout(()=>setDisplayedReference((displayedReference+1) % REFERENCES.length), 5000)
  
  useEffect(() => {
    setHydrated(true);
  }, []);
  if (!hydrated) {
    // Returns null on first render, so the client and server match
    return null;
  }
  if (typeof window !== "undefined") {
      window.addEventListener("scroll", reveal);
    }
  return (
    <>
      <Head>
        <title>Home | Matthew Torres</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Navigation></Navigation>
    <body>
      <div className={styles.backgroundLayer}>
          <img className={styles.headerImage} src="Matthew Torres.png"/>
          <h1 className={styles.pageTitle}>Matthew Torres</h1>
      </div>
      <div className={styles.references}>
        <p>"{REFERENCES[displayedReference].quote}"</p>
        <p>-{REFERENCES[displayedReference].author}</p>
      </div>
      <div className={styles.bio}>
        <h2>Bio</h2>
        <p>{BIO}</p>
    </div>
    </body>
    <Footer></Footer>
    </>
  );
}
