import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navigation from "./components/navigation";
import { useState, useEffect } from "react";
import Footer from "./components/footer";

const REFERENCES =
[
  {quote:"From beautiful ballads to raging rock and back again... elloquently excecutes each song with a dilligence audiences will come to expect", author:"The Tufts Daily"},
  {quote:"Testing a second quote", author:"The Tufts Daily"},
  {quote:"Testing a third quote", author:"The Tufts Daily"}
]
const BIO = 

<><p>Matthew Torres is a multi-faceted Software Engineer and Musician who holds a Bachelor's degree in Computer Science and Music from <a href="https://tufts.edu" target="_blank">Tufts University</a>. As a student in the <a href="https://engineering.tufts.edu/cs/" target="_blank">Tufts Department of Computer Science</a>, he served as an undergraduate teaching assistant for Web Programming (CS20), where he helped hundreds of students each year learn frontend and backend development techniques as well as simple database infrastructure. He went on to become a tech lead for <a href="https://jumbocode.org/" target="_blank">Jumbocode</a>, a student organization which delivers software projects to non-profit organizations. He applied skills learned through his studies as a two-summer intern at <a href="https://draper.com/" target="_blank">Draper</a>, where he delivered a dozen new features and improvements to Draper's Enterprise Software. To learn more about Matthew's Software Engineering work, view his <a href="/software">software portfolio</a>.</p>
  
  <p>Matthew is also an accomplished pianist, organist, music director, and composer. He served as Interim Organist and Choir Director at the <a href="https://uccgrafton.org" target="_blank">Congregational Church of Grafton (UCC)</a>, and has performed as an organist at the <a href="https://bcg1800.org" target="_blank">Baptist Church of Grafton</a> as well as <a href="https://chaplaincy.tufts.edu/" target="_blank">Tufts' Goddard Chapel</a>, and as a pianist at <a href="https://as.tufts.edu/music/" target="_blank">Tufts' Distler Hall</a> and countless other venues around Massachusetts. He has music directed seven theatrical productions, including Spring Awakening, Into the Woods, and Twelfth Night among others. He was also the President and Director of the  <a href="https://www.instagram.com/tuftsfreshman15/" target="_blank"></a>Tufts' Freshman 15 Jazz Big Band. To see Matthew's musical work, view his <a href="/music" target="_blank">music portfolio</a>.</p>
</>
function reveal() {
  var reveals = document.querySelectorAll(`.${styles.headerImage}, .${styles.pageTitle}`);
  console.log(reveals);
  for (var i = 0; i < reveals.length; i++) {
    var windowHeight = window.innerHeight;
    var elementTop = reveals[i].getBoundingClientRect().top;
    var elementVisible = 200;
    if (elementTop < windowHeight - elementVisible) {
      reveals[i].classList.add(styles.active);
    }
  }
}

export default function Home() {
  const [hydrated, setHydrated] = useState(false);
  const [displayedReference, setDisplayedReference] = useState(0);
  setTimeout(()=>setDisplayedReference((displayedReference+1) % REFERENCES.length), 5000)
  
  useEffect(() => {
    setHydrated(true);
  }, []);
  if (!hydrated) {
    // Returns null on first render, so the client and server match
    return null;
  }
  if (typeof window !== "undefined") {
      window.addEventListener("scroll", reveal);
    }
  return (
    <>
      <Head>
        <title>Home | Matthew Torres</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Navigation></Navigation>
    <body>
      <div className={styles.backgroundLayer}>
          <img className={styles.headerImage} src="Matthew Torres.png"/>
          <h1 className={styles.pageTitle}>Matthew Torres</h1>
      </div>
      <div className={styles.references}>
        <p>"{REFERENCES[displayedReference].quote}"</p>
        <p>-{REFERENCES[displayedReference].author}</p>
      </div>
      <div className={styles.bio}>
        <h2>Bio</h2>
        {BIO}
    </div>
    </body>
    <Footer></Footer>
    </>
  );
}
